#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh gradlew
#
#       If you are stuck, you can try installing a 'posix' compatibility package.
#
#   (2) This script guesses the location of the `JAVA_HOME` variable.
#       If you want to be sure, set the environment variable `JAVA_HOME` before running.
#
##############################################################################

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# shellcheck disable=SC2016
if [ -z "$JAVA_HOME" ]; then
  JAVA_HOME="$(command -v java 2>/dev/null | xargs dirname | xargs dirname | xargs dirname | xargs realpath 2>/dev/null || echo '')"
fi

# Apply that to the environment.
JAVA_HOME="${JAVA_HOME:-$(dirname "$(command -v java)")}"
JAVA_OPTS="${JAVA_OPTS:-$DEFAULT_JVM_OPTS}"

# The location of the gradle wrapper jar.
WRAPPER_JAR="gradle/wrapper/gradle-wrapper.jar"
WRAPPER_SCRIPT="gradle/wrapper/gradle-wrapper.jar"

# Find the application home.
APP_HOME=$(cd "$(dirname "$0")" && pwd)

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
GRADLE_OPTS="${GRADLE_OPTS:-$DEFAULT_JVM_OPTS}"

GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"

# The Gradle wrapper jar.
if [ ! -f "$WRAPPER_JAR" ]; then
  echo "ERROR: Could not find Gradle wrapper jar: $WRAPPER_JAR"
  echo "Please run 'gradle wrapper' to generate it."
  exit 1
fi

exec "$JAVA_HOME/bin/java" $JAVA_OPTS $GRADLE_OPTS -jar "$WRAPPER_JAR" "$@"
